FROM python:3.7

RUN mkdir /app
WORKDIR /app

COPY requirements.txt /app
COPY acme_core.py /app
COPY acme_server.py /app

RUN pip install -r requirements.txt

ENTRYPOINT [ "python3", "acme_server.py" ]
