version: '3'
services:
    metricserver:
      build:
        context: ./
        dockerfile: Dockerfile.MetricServer
      command: ['5000']
      ports: 
          - "5000:5000"
    normalacmeserver_a:
      build:
        context: ./
        dockerfile: Dockerfile.AcmeServer
      command: ['http://metricserver:5000', '--sleep', '10']
    unusualacmeserver_a:
      build:
        context: ./
        dockerfile: Dockerfile.AcmeServer
      command: ['http://metricserver:5000', '--sleep', '20', '--send-unusual']