FROM python:3.7

RUN mkdir /app
WORKDIR /app

COPY requirements.txt /app
COPY metric_core.py /app
COPY metric_server.py /app

RUN pip install -r requirements.txt

ENV FLASK_APP=metric_server

ENTRYPOINT [ "flask", "run", "-h", "0.0.0.0", "-p" ]
